/*
 * configapi
 * Config API lets you easily manage configuration at scale.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.cloudmersive.client.model.SettingValue;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Result of enumerating settings
 */
@ApiModel(description = "Result of enumerating settings")
@JsonPropertyOrder({
  ListSettingsResponse.JSON_PROPERTY_SETTINGS
})
@JsonTypeName("ListSettingsResponse")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-11-14T13:23:35.485-08:00[America/Los_Angeles]")
public class ListSettingsResponse {
  public static final String JSON_PROPERTY_SETTINGS = "Settings";
  private List<SettingValue> settings = null;


  public ListSettingsResponse settings(List<SettingValue> settings) {
    
    this.settings = settings;
    return this;
  }

  public ListSettingsResponse addSettingsItem(SettingValue settingsItem) {
    if (this.settings == null) {
      this.settings = new ArrayList<SettingValue>();
    }
    this.settings.add(settingsItem);
    return this;
  }

   /**
   * Settings in the bucket
   * @return settings
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Settings in the bucket")
  @JsonProperty(JSON_PROPERTY_SETTINGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<SettingValue> getSettings() {
    return settings;
  }


  public void setSettings(List<SettingValue> settings) {
    this.settings = settings;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListSettingsResponse listSettingsResponse = (ListSettingsResponse) o;
    return Objects.equals(this.settings, listSettingsResponse.settings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(settings);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListSettingsResponse {\n");
    sb.append("    settings: ").append(toIndentedString(settings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

