/*
 * convertapi
 * Convert API lets you effortlessly convert file formats and types.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.rt.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Base64DetectResponse
 */
class Base64DetectResponseTest {
    private final Base64DetectResponse model = new Base64DetectResponse();

    /**
     * Model tests for Base64DetectResponse
     */
    @Test
    void testBase64DetectResponse() {
        // TODO: test Base64DetectResponse
    }

    /**
     * Test the property 'successful'
     */
    @Test
    void successfulTest() {
        // TODO: test successful
    }

    /**
     * Test the property 'isBase64Encoded'
     */
    @Test
    void isBase64EncodedTest() {
        // TODO: test isBase64Encoded
    }

}
