/*
 * nlpapiv2
 * The powerful Natural Language Processing APIs (v2) let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.rt.model;

import com.cloudmersive.client.rt.model.CorrectWordInSentence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CheckSentenceResponse
 */
public class CheckSentenceResponseTest {
    private final CheckSentenceResponse model = new CheckSentenceResponse();

    /**
     * Model tests for CheckSentenceResponse
     */
    @Test
    public void testCheckSentenceResponse() {
        // TODO: test CheckSentenceResponse
    }

    /**
     * Test the property 'incorrectCount'
     */
    @Test
    public void incorrectCountTest() {
        // TODO: test incorrectCount
    }

    /**
     * Test the property 'words'
     */
    @Test
    public void wordsTest() {
        // TODO: test words
    }

}
