/*
 * imageapi
 * Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.rt.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DetectedLicensePlate
 */
class DetectedLicensePlateTest {
    private final DetectedLicensePlate model = new DetectedLicensePlate();

    /**
     * Model tests for DetectedLicensePlate
     */
    @Test
    void testDetectedLicensePlate() {
        // TODO: test DetectedLicensePlate
    }

    /**
     * Test the property 'licensePlateTextBestMatch'
     */
    @Test
    void licensePlateTextBestMatchTest() {
        // TODO: test licensePlateTextBestMatch
    }

    /**
     * Test the property 'licensePlateTextRunnerUp'
     */
    @Test
    void licensePlateTextRunnerUpTest() {
        // TODO: test licensePlateTextRunnerUp
    }

    /**
     * Test the property 'locationX'
     */
    @Test
    void locationXTest() {
        // TODO: test locationX
    }

    /**
     * Test the property 'locationY'
     */
    @Test
    void locationYTest() {
        // TODO: test locationY
    }

    /**
     * Test the property 'width'
     */
    @Test
    void widthTest() {
        // TODO: test width
    }

    /**
     * Test the property 'height'
     */
    @Test
    void heightTest() {
        // TODO: test height
    }

    /**
     * Test the property 'licensePlateRecognitionConfidenceLevel'
     */
    @Test
    void licensePlateRecognitionConfidenceLevelTest() {
        // TODO: test licensePlateRecognitionConfidenceLevel
    }

}
