/*
 * convertapi
 * Convert API lets you effortlessly convert file formats and types.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.rt.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DocxCellStyle
 */
class DocxCellStyleTest {
    private final DocxCellStyle model = new DocxCellStyle();

    /**
     * Model tests for DocxCellStyle
     */
    @Test
    void testDocxCellStyle() {
        // TODO: test DocxCellStyle
    }

    /**
     * Test the property 'path'
     */
    @Test
    void pathTest() {
        // TODO: test path
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'formatID'
     */
    @Test
    void formatIDTest() {
        // TODO: test formatID
    }

    /**
     * Test the property 'builtInID'
     */
    @Test
    void builtInIDTest() {
        // TODO: test builtInID
    }

}
