/*
 * convertapi
 * Convert API lets you effortlessly convert file formats and types.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.rt.model;

import com.cloudmersive.client.rt.model.DocxParagraph;
import com.cloudmersive.client.rt.model.DocxSection;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DocxHeader
 */
public class DocxHeaderTest {
    private final DocxHeader model = new DocxHeader();

    /**
     * Model tests for DocxHeader
     */
    @Test
    public void testDocxHeader() {
        // TODO: test DocxHeader
    }

    /**
     * Test the property 'path'
     */
    @Test
    public void pathTest() {
        // TODO: test path
    }

    /**
     * Test the property 'paragraphs'
     */
    @Test
    public void paragraphsTest() {
        // TODO: test paragraphs
    }

    /**
     * Test the property 'sectionsWithHeader'
     */
    @Test
    public void sectionsWithHeaderTest() {
        // TODO: test sectionsWithHeader
    }

}
