/*
 * convertapi
 * Convert API lets you effortlessly convert file formats and types.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.rt.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DocxRemoveObjectRequest
 */
public class DocxRemoveObjectRequestTest {
    private final DocxRemoveObjectRequest model = new DocxRemoveObjectRequest();

    /**
     * Model tests for DocxRemoveObjectRequest
     */
    @Test
    public void testDocxRemoveObjectRequest() {
        // TODO: test DocxRemoveObjectRequest
    }

    /**
     * Test the property 'inputFileBytes'
     */
    @Test
    public void inputFileBytesTest() {
        // TODO: test inputFileBytes
    }

    /**
     * Test the property 'inputFileUrl'
     */
    @Test
    public void inputFileUrlTest() {
        // TODO: test inputFileUrl
    }

    /**
     * Test the property 'pathToObjectToRemove'
     */
    @Test
    public void pathToObjectToRemoveTest() {
        // TODO: test pathToObjectToRemove
    }

}
