/*
 * imageapi
 * Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.rt.model;

import com.cloudmersive.client.rt.model.FacePoint;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FaceWithLandmarks
 */
class FaceWithLandmarksTest {
    private final FaceWithLandmarks model = new FaceWithLandmarks();

    /**
     * Model tests for FaceWithLandmarks
     */
    @Test
    void testFaceWithLandmarks() {
        // TODO: test FaceWithLandmarks
    }

    /**
     * Test the property 'leftX'
     */
    @Test
    void leftXTest() {
        // TODO: test leftX
    }

    /**
     * Test the property 'topY'
     */
    @Test
    void topYTest() {
        // TODO: test topY
    }

    /**
     * Test the property 'rightX'
     */
    @Test
    void rightXTest() {
        // TODO: test rightX
    }

    /**
     * Test the property 'bottomY'
     */
    @Test
    void bottomYTest() {
        // TODO: test bottomY
    }

    /**
     * Test the property 'leftEyebrow'
     */
    @Test
    void leftEyebrowTest() {
        // TODO: test leftEyebrow
    }

    /**
     * Test the property 'rightEyebrow'
     */
    @Test
    void rightEyebrowTest() {
        // TODO: test rightEyebrow
    }

    /**
     * Test the property 'leftEye'
     */
    @Test
    void leftEyeTest() {
        // TODO: test leftEye
    }

    /**
     * Test the property 'rightEye'
     */
    @Test
    void rightEyeTest() {
        // TODO: test rightEye
    }

    /**
     * Test the property 'bottomAndSidesOfFace'
     */
    @Test
    void bottomAndSidesOfFaceTest() {
        // TODO: test bottomAndSidesOfFace
    }

    /**
     * Test the property 'noseBridge'
     */
    @Test
    void noseBridgeTest() {
        // TODO: test noseBridge
    }

    /**
     * Test the property 'noseBottom'
     */
    @Test
    void noseBottomTest() {
        // TODO: test noseBottom
    }

    /**
     * Test the property 'lipsInnerOutline'
     */
    @Test
    void lipsInnerOutlineTest() {
        // TODO: test lipsInnerOutline
    }

    /**
     * Test the property 'lipsOuterOutline'
     */
    @Test
    void lipsOuterOutlineTest() {
        // TODO: test lipsOuterOutline
    }

}
