/*
 * imageapi
 * Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.rt.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FaceMatch
 */
class FaceMatchTest {
    private final FaceMatch model = new FaceMatch();

    /**
     * Model tests for FaceMatch
     */
    @Test
    void testFaceMatch() {
        // TODO: test FaceMatch
    }

    /**
     * Test the property 'leftX'
     */
    @Test
    void leftXTest() {
        // TODO: test leftX
    }

    /**
     * Test the property 'topY'
     */
    @Test
    void topYTest() {
        // TODO: test topY
    }

    /**
     * Test the property 'rightX'
     */
    @Test
    void rightXTest() {
        // TODO: test rightX
    }

    /**
     * Test the property 'bottomY'
     */
    @Test
    void bottomYTest() {
        // TODO: test bottomY
    }

    /**
     * Test the property 'highConfidenceMatch'
     */
    @Test
    void highConfidenceMatchTest() {
        // TODO: test highConfidenceMatch
    }

    /**
     * Test the property 'matchScore'
     */
    @Test
    void matchScoreTest() {
        // TODO: test matchScore
    }

}
