/*
 * imageapi
 * Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.rt.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for FacePoint
 */
public class FacePointTest {
    private final FacePoint model = new FacePoint();

    /**
     * Model tests for FacePoint
     */
    @Test
    public void testFacePoint() {
        // TODO: test FacePoint
    }

    /**
     * Test the property 'X'
     */
    @Test
    public void XTest() {
        // TODO: test X
    }

    /**
     * Test the property 'Y'
     */
    @Test
    public void YTest() {
        // TODO: test Y
    }

}
