/*
 * ocrapi
 * The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.rt.model;

import com.cloudmersive.client.rt.model.FieldResult;
import com.cloudmersive.client.rt.model.TableResult;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for FormRecognitionResult
 */
public class FormRecognitionResultTest {
    private final FormRecognitionResult model = new FormRecognitionResult();

    /**
     * Model tests for FormRecognitionResult
     */
    @Test
    public void testFormRecognitionResult() {
        // TODO: test FormRecognitionResult
    }

    /**
     * Test the property 'successful'
     */
    @Test
    public void successfulTest() {
        // TODO: test successful
    }

    /**
     * Test the property 'fieldValueExtractionResult'
     */
    @Test
    public void fieldValueExtractionResultTest() {
        // TODO: test fieldValueExtractionResult
    }

    /**
     * Test the property 'tableValueExtractionResults'
     */
    @Test
    public void tableValueExtractionResultsTest() {
        // TODO: test tableValueExtractionResults
    }

    /**
     * Test the property 'diagnostics'
     */
    @Test
    public void diagnosticsTest() {
        // TODO: test diagnostics
    }

    /**
     * Test the property 'bestMatchFormSettingName'
     */
    @Test
    public void bestMatchFormSettingNameTest() {
        // TODO: test bestMatchFormSettingName
    }

}
