/*
 * imageapi
 * Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.rt.model;

import com.cloudmersive.client.rt.model.PersonWithGender;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GenderDetectionResult
 */
class GenderDetectionResultTest {
    private final GenderDetectionResult model = new GenderDetectionResult();

    /**
     * Model tests for GenderDetectionResult
     */
    @Test
    void testGenderDetectionResult() {
        // TODO: test GenderDetectionResult
    }

    /**
     * Test the property 'successful'
     */
    @Test
    void successfulTest() {
        // TODO: test successful
    }

    /**
     * Test the property 'personWithGender'
     */
    @Test
    void personWithGenderTest() {
        // TODO: test personWithGender
    }

    /**
     * Test the property 'peopleIdentified'
     */
    @Test
    void peopleIdentifiedTest() {
        // TODO: test peopleIdentified
    }

}
