/*
 * convertapi
 * Convert API lets you effortlessly convert file formats and types.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.rt.model;

import com.cloudmersive.client.rt.model.DocxContentControl;
import com.cloudmersive.client.rt.model.HandlebarFormField;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetDocxGetFormFieldsResponse
 */
public class GetDocxGetFormFieldsResponseTest {
    private final GetDocxGetFormFieldsResponse model = new GetDocxGetFormFieldsResponse();

    /**
     * Model tests for GetDocxGetFormFieldsResponse
     */
    @Test
    public void testGetDocxGetFormFieldsResponse() {
        // TODO: test GetDocxGetFormFieldsResponse
    }

    /**
     * Test the property 'successful'
     */
    @Test
    public void successfulTest() {
        // TODO: test successful
    }

    /**
     * Test the property 'contentControls'
     */
    @Test
    public void contentControlsTest() {
        // TODO: test contentControls
    }

    /**
     * Test the property 'handlebarFormFields'
     */
    @Test
    public void handlebarFormFieldsTest() {
        // TODO: test handlebarFormFields
    }

}
