/*
 * convertapi
 * Convert API lets you effortlessly convert file formats and types.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.rt.model;

import com.cloudmersive.client.rt.model.DocxMetadataCustomProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetDocxMetadataPropertiesResponse
 */
class GetDocxMetadataPropertiesResponseTest {
    private final GetDocxMetadataPropertiesResponse model = new GetDocxMetadataPropertiesResponse();

    /**
     * Model tests for GetDocxMetadataPropertiesResponse
     */
    @Test
    void testGetDocxMetadataPropertiesResponse() {
        // TODO: test GetDocxMetadataPropertiesResponse
    }

    /**
     * Test the property 'company'
     */
    @Test
    void companyTest() {
        // TODO: test company
    }

    /**
     * Test the property 'manager'
     */
    @Test
    void managerTest() {
        // TODO: test manager
    }

    /**
     * Test the property 'applicationVersion'
     */
    @Test
    void applicationVersionTest() {
        // TODO: test applicationVersion
    }

    /**
     * Test the property 'wordCount'
     */
    @Test
    void wordCountTest() {
        // TODO: test wordCount
    }

    /**
     * Test the property 'lineCount'
     */
    @Test
    void lineCountTest() {
        // TODO: test lineCount
    }

    /**
     * Test the property 'paragraphCount'
     */
    @Test
    void paragraphCountTest() {
        // TODO: test paragraphCount
    }

    /**
     * Test the property 'pageCount'
     */
    @Test
    void pageCountTest() {
        // TODO: test pageCount
    }

    /**
     * Test the property 'customProperties'
     */
    @Test
    void customPropertiesTest() {
        // TODO: test customProperties
    }

    /**
     * Test the property 'successful'
     */
    @Test
    void successfulTest() {
        // TODO: test successful
    }

}
