/*
 * convertapi
 * Convert API lets you effortlessly convert file formats and types.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.rt.model;

import com.cloudmersive.client.rt.model.DocxComment;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetDocxCommentsResponse
 */
class GetDocxCommentsResponseTest {
    private final GetDocxCommentsResponse model = new GetDocxCommentsResponse();

    /**
     * Model tests for GetDocxCommentsResponse
     */
    @Test
    void testGetDocxCommentsResponse() {
        // TODO: test GetDocxCommentsResponse
    }

    /**
     * Test the property 'successful'
     */
    @Test
    void successfulTest() {
        // TODO: test successful
    }

    /**
     * Test the property 'comments'
     */
    @Test
    void commentsTest() {
        // TODO: test comments
    }

    /**
     * Test the property 'commentCount'
     */
    @Test
    void commentCountTest() {
        // TODO: test commentCount
    }

}
