/*
 * convertapi
 * Convert API lets you effortlessly convert file formats and types.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.rt.model;

import com.cloudmersive.client.rt.model.ExifValue;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetImageInfoResult
 */
class GetImageInfoResultTest {
    private final GetImageInfoResult model = new GetImageInfoResult();

    /**
     * Model tests for GetImageInfoResult
     */
    @Test
    void testGetImageInfoResult() {
        // TODO: test GetImageInfoResult
    }

    /**
     * Test the property 'successful'
     */
    @Test
    void successfulTest() {
        // TODO: test successful
    }

    /**
     * Test the property 'colorSpace'
     */
    @Test
    void colorSpaceTest() {
        // TODO: test colorSpace
    }

    /**
     * Test the property 'colorType'
     */
    @Test
    void colorTypeTest() {
        // TODO: test colorType
    }

    /**
     * Test the property 'width'
     */
    @Test
    void widthTest() {
        // TODO: test width
    }

    /**
     * Test the property 'height'
     */
    @Test
    void heightTest() {
        // TODO: test height
    }

    /**
     * Test the property 'compressionLevel'
     */
    @Test
    void compressionLevelTest() {
        // TODO: test compressionLevel
    }

    /**
     * Test the property 'imageHashSignature'
     */
    @Test
    void imageHashSignatureTest() {
        // TODO: test imageHashSignature
    }

    /**
     * Test the property 'hasTransparency'
     */
    @Test
    void hasTransparencyTest() {
        // TODO: test hasTransparency
    }

    /**
     * Test the property 'mimeType'
     */
    @Test
    void mimeTypeTest() {
        // TODO: test mimeType
    }

    /**
     * Test the property 'imageFormat'
     */
    @Test
    void imageFormatTest() {
        // TODO: test imageFormat
    }

    /**
     * Test the property 'dpIUnit'
     */
    @Test
    void dpIUnitTest() {
        // TODO: test dpIUnit
    }

    /**
     * Test the property 'DPI'
     */
    @Test
    void DPITest() {
        // TODO: test DPI
    }

    /**
     * Test the property 'colorCount'
     */
    @Test
    void colorCountTest() {
        // TODO: test colorCount
    }

    /**
     * Test the property 'bitDepth'
     */
    @Test
    void bitDepthTest() {
        // TODO: test bitDepth
    }

    /**
     * Test the property 'comment'
     */
    @Test
    void commentTest() {
        // TODO: test comment
    }

    /**
     * Test the property 'exifProfileName'
     */
    @Test
    void exifProfileNameTest() {
        // TODO: test exifProfileName
    }

    /**
     * Test the property 'exifValues'
     */
    @Test
    void exifValuesTest() {
        // TODO: test exifValues
    }

}
