/*
 * convertapi
 * Convert API lets you effortlessly convert file formats and types.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.rt.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for HandlebarFormField
 */
public class HandlebarFormFieldTest {
    private final HandlebarFormField model = new HandlebarFormField();

    /**
     * Model tests for HandlebarFormField
     */
    @Test
    public void testHandlebarFormField() {
        // TODO: test HandlebarFormField
    }

    /**
     * Test the property 'formFieldTitle'
     */
    @Test
    public void formFieldTitleTest() {
        // TODO: test formFieldTitle
    }

}
