/*
 * configapi
 * Config API lets you easily manage configuration at scale.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.rt.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for HttpOrchestrationResponse
 */
class HttpOrchestrationResponseTest {
    private final HttpOrchestrationResponse model = new HttpOrchestrationResponse();

    /**
     * Model tests for HttpOrchestrationResponse
     */
    @Test
    void testHttpOrchestrationResponse() {
        // TODO: test HttpOrchestrationResponse
    }

    /**
     * Test the property 'successful'
     */
    @Test
    void successfulTest() {
        // TODO: test successful
    }

    /**
     * Test the property 'tasksCompleted'
     */
    @Test
    void tasksCompletedTest() {
        // TODO: test tasksCompleted
    }

    /**
     * Test the property 'outputStringType'
     */
    @Test
    void outputStringTypeTest() {
        // TODO: test outputStringType
    }

    /**
     * Test the property 'outputBinaryType'
     */
    @Test
    void outputBinaryTypeTest() {
        // TODO: test outputBinaryType
    }

}
