/*
 * configapi
 * Config API lets you easily manage configuration at scale.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.rt.model;

import com.cloudmersive.client.rt.model.TaskOutputReference;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for HttpRawBinaryParameter
 */
public class HttpRawBinaryParameterTest {
    private final HttpRawBinaryParameter model = new HttpRawBinaryParameter();

    /**
     * Model tests for HttpRawBinaryParameter
     */
    @Test
    public void testHttpRawBinaryParameter() {
        // TODO: test HttpRawBinaryParameter
    }

    /**
     * Test the property 'parameterValue'
     */
    @Test
    public void parameterValueTest() {
        // TODO: test parameterValue
    }

    /**
     * Test the property 'useOutputFromPreviousTask'
     */
    @Test
    public void useOutputFromPreviousTaskTest() {
        // TODO: test useOutputFromPreviousTask
    }

}
