/*
 * imageapi
 * Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.rt.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ImageMetadataExifValue
 */
class ImageMetadataExifValueTest {
    private final ImageMetadataExifValue model = new ImageMetadataExifValue();

    /**
     * Model tests for ImageMetadataExifValue
     */
    @Test
    void testImageMetadataExifValue() {
        // TODO: test ImageMetadataExifValue
    }

    /**
     * Test the property 'tag'
     */
    @Test
    void tagTest() {
        // TODO: test tag
    }

    /**
     * Test the property 'dataType'
     */
    @Test
    void dataTypeTest() {
        // TODO: test dataType
    }

    /**
     * Test the property 'dataValue'
     */
    @Test
    void dataValueTest() {
        // TODO: test dataValue
    }

}
