/*
 * validateapi
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.rt.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for LeadEnrichmentResponse
 */
class LeadEnrichmentResponseTest {
    private final LeadEnrichmentResponse model = new LeadEnrichmentResponse();

    /**
     * Model tests for LeadEnrichmentResponse
     */
    @Test
    void testLeadEnrichmentResponse() {
        // TODO: test LeadEnrichmentResponse
    }

    /**
     * Test the property 'successful'
     */
    @Test
    void successfulTest() {
        // TODO: test successful
    }

    /**
     * Test the property 'leadType'
     */
    @Test
    void leadTypeTest() {
        // TODO: test leadType
    }

    /**
     * Test the property 'contactBusinessEmail'
     */
    @Test
    void contactBusinessEmailTest() {
        // TODO: test contactBusinessEmail
    }

    /**
     * Test the property 'contactFirstName'
     */
    @Test
    void contactFirstNameTest() {
        // TODO: test contactFirstName
    }

    /**
     * Test the property 'contactLastName'
     */
    @Test
    void contactLastNameTest() {
        // TODO: test contactLastName
    }

    /**
     * Test the property 'contactGender'
     */
    @Test
    void contactGenderTest() {
        // TODO: test contactGender
    }

    /**
     * Test the property 'companyName'
     */
    @Test
    void companyNameTest() {
        // TODO: test companyName
    }

    /**
     * Test the property 'companyDomainName'
     */
    @Test
    void companyDomainNameTest() {
        // TODO: test companyDomainName
    }

    /**
     * Test the property 'companyHouseNumber'
     */
    @Test
    void companyHouseNumberTest() {
        // TODO: test companyHouseNumber
    }

    /**
     * Test the property 'companyStreet'
     */
    @Test
    void companyStreetTest() {
        // TODO: test companyStreet
    }

    /**
     * Test the property 'companyCity'
     */
    @Test
    void companyCityTest() {
        // TODO: test companyCity
    }

    /**
     * Test the property 'companyStateOrProvince'
     */
    @Test
    void companyStateOrProvinceTest() {
        // TODO: test companyStateOrProvince
    }

    /**
     * Test the property 'companyPostalCode'
     */
    @Test
    void companyPostalCodeTest() {
        // TODO: test companyPostalCode
    }

    /**
     * Test the property 'companyCountry'
     */
    @Test
    void companyCountryTest() {
        // TODO: test companyCountry
    }

    /**
     * Test the property 'companyCountryCode'
     */
    @Test
    void companyCountryCodeTest() {
        // TODO: test companyCountryCode
    }

    /**
     * Test the property 'companyTelephone'
     */
    @Test
    void companyTelephoneTest() {
        // TODO: test companyTelephone
    }

    /**
     * Test the property 'companyVATNumber'
     */
    @Test
    void companyVATNumberTest() {
        // TODO: test companyVATNumber
    }

    /**
     * Test the property 'employeeCount'
     */
    @Test
    void employeeCountTest() {
        // TODO: test employeeCount
    }

}
