/*
 * convertapi
 * Convert API lets you effortlessly convert file formats and types.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.rt.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MergeJobStatusResult
 */
class MergeJobStatusResultTest {
    private final MergeJobStatusResult model = new MergeJobStatusResult();

    /**
     * Model tests for MergeJobStatusResult
     */
    @Test
    void testMergeJobStatusResult() {
        // TODO: test MergeJobStatusResult
    }

    /**
     * Test the property 'successful'
     */
    @Test
    void successfulTest() {
        // TODO: test successful
    }

    /**
     * Test the property 'asyncJobStatus'
     */
    @Test
    void asyncJobStatusTest() {
        // TODO: test asyncJobStatus
    }

    /**
     * Test the property 'asyncJobID'
     */
    @Test
    void asyncJobIDTest() {
        // TODO: test asyncJobID
    }

    /**
     * Test the property 'fileOutputResult'
     */
    @Test
    void fileOutputResultTest() {
        // TODO: test fileOutputResult
    }

    /**
     * Test the property 'errorMessage'
     */
    @Test
    void errorMessageTest() {
        // TODO: test errorMessage
    }

}
