/*
 * dataintegrationapi
 * Easily and directly query database backup files, convert into other file formats.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.rt.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MssqlTable
 */
class MssqlTableTest {
    private final MssqlTable model = new MssqlTable();

    /**
     * Model tests for MssqlTable
     */
    @Test
    void testMssqlTable() {
        // TODO: test MssqlTable
    }

    /**
     * Test the property 'schemaName'
     */
    @Test
    void schemaNameTest() {
        // TODO: test schemaName
    }

    /**
     * Test the property 'tableName'
     */
    @Test
    void tableNameTest() {
        // TODO: test tableName
    }

}
