/*
 * ocrapi
 * The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.rt.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OcrWordElement
 */
class OcrWordElementTest {
    private final OcrWordElement model = new OcrWordElement();

    /**
     * Model tests for OcrWordElement
     */
    @Test
    void testOcrWordElement() {
        // TODO: test OcrWordElement
    }

    /**
     * Test the property 'wordText'
     */
    @Test
    void wordTextTest() {
        // TODO: test wordText
    }

    /**
     * Test the property 'lineNumber'
     */
    @Test
    void lineNumberTest() {
        // TODO: test lineNumber
    }

    /**
     * Test the property 'wordNumber'
     */
    @Test
    void wordNumberTest() {
        // TODO: test wordNumber
    }

    /**
     * Test the property 'xleft'
     */
    @Test
    void xleftTest() {
        // TODO: test xleft
    }

    /**
     * Test the property 'ytop'
     */
    @Test
    void ytopTest() {
        // TODO: test ytop
    }

    /**
     * Test the property 'width'
     */
    @Test
    void widthTest() {
        // TODO: test width
    }

    /**
     * Test the property 'height'
     */
    @Test
    void heightTest() {
        // TODO: test height
    }

    /**
     * Test the property 'confidenceLevel'
     */
    @Test
    void confidenceLevelTest() {
        // TODO: test confidenceLevel
    }

    /**
     * Test the property 'blockNumber'
     */
    @Test
    void blockNumberTest() {
        // TODO: test blockNumber
    }

    /**
     * Test the property 'paragraphNumber'
     */
    @Test
    void paragraphNumberTest() {
        // TODO: test paragraphNumber
    }

    /**
     * Test the property 'pageNumber'
     */
    @Test
    void pageNumberTest() {
        // TODO: test pageNumber
    }

}
