/*
 * ocrapi
 * The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.rt.model;

import com.cloudmersive.client.rt.model.OcrPageResultWithLinesWithLocation;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PdfToLinesWithLocationResult
 */
class PdfToLinesWithLocationResultTest {
    private final PdfToLinesWithLocationResult model = new PdfToLinesWithLocationResult();

    /**
     * Model tests for PdfToLinesWithLocationResult
     */
    @Test
    void testPdfToLinesWithLocationResult() {
        // TODO: test PdfToLinesWithLocationResult
    }

    /**
     * Test the property 'successful'
     */
    @Test
    void successfulTest() {
        // TODO: test successful
    }

    /**
     * Test the property 'ocrPages'
     */
    @Test
    void ocrPagesTest() {
        // TODO: test ocrPages
    }

}
