/*
 * validateapi
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.rt.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PublicHolidayOccurrence
 */
public class PublicHolidayOccurrenceTest {
    private final PublicHolidayOccurrence model = new PublicHolidayOccurrence();

    /**
     * Model tests for PublicHolidayOccurrence
     */
    @Test
    public void testPublicHolidayOccurrence() {
        // TODO: test PublicHolidayOccurrence
    }

    /**
     * Test the property 'englishName'
     */
    @Test
    public void englishNameTest() {
        // TODO: test englishName
    }

    /**
     * Test the property 'localName'
     */
    @Test
    public void localNameTest() {
        // TODO: test localName
    }

    /**
     * Test the property 'occurrenceDate'
     */
    @Test
    public void occurrenceDateTest() {
        // TODO: test occurrenceDate
    }

    /**
     * Test the property 'holidayType'
     */
    @Test
    public void holidayTypeTest() {
        // TODO: test holidayType
    }

    /**
     * Test the property 'nationwaide'
     */
    @Test
    public void nationwaideTest() {
        // TODO: test nationwaide
    }

}
