/*
 * convertapi
 * Convert API lets you effortlessly convert file formats and types.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.rt.model;

import com.cloudmersive.client.rt.model.XlsxSpreadsheetCell;
import com.cloudmersive.client.rt.model.XlsxWorksheet;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SetXlsxCellRequest
 */
public class SetXlsxCellRequestTest {
    private final SetXlsxCellRequest model = new SetXlsxCellRequest();

    /**
     * Model tests for SetXlsxCellRequest
     */
    @Test
    public void testSetXlsxCellRequest() {
        // TODO: test SetXlsxCellRequest
    }

    /**
     * Test the property 'inputFileBytes'
     */
    @Test
    public void inputFileBytesTest() {
        // TODO: test inputFileBytes
    }

    /**
     * Test the property 'inputFileUrl'
     */
    @Test
    public void inputFileUrlTest() {
        // TODO: test inputFileUrl
    }

    /**
     * Test the property 'worksheetToUpdate'
     */
    @Test
    public void worksheetToUpdateTest() {
        // TODO: test worksheetToUpdate
    }

    /**
     * Test the property 'rowIndex'
     */
    @Test
    public void rowIndexTest() {
        // TODO: test rowIndex
    }

    /**
     * Test the property 'cellIndex'
     */
    @Test
    public void cellIndexTest() {
        // TODO: test cellIndex
    }

    /**
     * Test the property 'cellValue'
     */
    @Test
    public void cellValueTest() {
        // TODO: test cellValue
    }

}
