/*
 * nlpapiv2
 * The powerful Natural Language Processing APIs (v2) let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.rt.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SimilarityAnalysisResponse
 */
public class SimilarityAnalysisResponseTest {
    private final SimilarityAnalysisResponse model = new SimilarityAnalysisResponse();

    /**
     * Model tests for SimilarityAnalysisResponse
     */
    @Test
    public void testSimilarityAnalysisResponse() {
        // TODO: test SimilarityAnalysisResponse
    }

    /**
     * Test the property 'successful'
     */
    @Test
    public void successfulTest() {
        // TODO: test successful
    }

    /**
     * Test the property 'similarityScoreResult'
     */
    @Test
    public void similarityScoreResultTest() {
        // TODO: test similarityScoreResult
    }

    /**
     * Test the property 'sentenceCount'
     */
    @Test
    public void sentenceCountTest() {
        // TODO: test sentenceCount
    }

}
