/*
 * validateapi
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.rt.model;

import com.cloudmersive.client.rt.model.SqlInjectionCheckRequestItem;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SqlInjectionCheckBatchRequest
 */
public class SqlInjectionCheckBatchRequestTest {
    private final SqlInjectionCheckBatchRequest model = new SqlInjectionCheckBatchRequest();

    /**
     * Model tests for SqlInjectionCheckBatchRequest
     */
    @Test
    public void testSqlInjectionCheckBatchRequest() {
        // TODO: test SqlInjectionCheckBatchRequest
    }

    /**
     * Test the property 'requestItems'
     */
    @Test
    public void requestItemsTest() {
        // TODO: test requestItems
    }

    /**
     * Test the property 'detectionLevel'
     */
    @Test
    public void detectionLevelTest() {
        // TODO: test detectionLevel
    }

}
