/*
 * validateapi
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.rt.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ValidateUrlResponseFull
 */
class ValidateUrlResponseFullTest {
    private final ValidateUrlResponseFull model = new ValidateUrlResponseFull();

    /**
     * Model tests for ValidateUrlResponseFull
     */
    @Test
    void testValidateUrlResponseFull() {
        // TODO: test ValidateUrlResponseFull
    }

    /**
     * Test the property 'validURL'
     */
    @Test
    void validURLTest() {
        // TODO: test validURL
    }

    /**
     * Test the property 'validSyntax'
     */
    @Test
    void validSyntaxTest() {
        // TODO: test validSyntax
    }

    /**
     * Test the property 'validDomain'
     */
    @Test
    void validDomainTest() {
        // TODO: test validDomain
    }

    /**
     * Test the property 'validEndpoint'
     */
    @Test
    void validEndpointTest() {
        // TODO: test validEndpoint
    }

    /**
     * Test the property 'wellFormedURL'
     */
    @Test
    void wellFormedURLTest() {
        // TODO: test wellFormedURL
    }

}
