/*
 * videoapi
 * The video APIs help you convert, encode, and transcode videos.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.rt.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for VideoFile
 */
class VideoFileTest {
    private final VideoFile model = new VideoFile();

    /**
     * Model tests for VideoFile
     */
    @Test
    void testVideoFile() {
        // TODO: test VideoFile
    }

    /**
     * Test the property 'videoNumber'
     */
    @Test
    void videoNumberTest() {
        // TODO: test videoNumber
    }

    /**
     * Test the property 'content'
     */
    @Test
    void contentTest() {
        // TODO: test content
    }

}
