/*
 * convertapi
 * Convert API lets you effortlessly convert file formats and types.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.rt.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for XlsxImage
 */
public class XlsxImageTest {
    private final XlsxImage model = new XlsxImage();

    /**
     * Model tests for XlsxImage
     */
    @Test
    public void testXlsxImage() {
        // TODO: test XlsxImage
    }

    /**
     * Test the property 'path'
     */
    @Test
    public void pathTest() {
        // TODO: test path
    }

    /**
     * Test the property 'imageDataEmbedId'
     */
    @Test
    public void imageDataEmbedIdTest() {
        // TODO: test imageDataEmbedId
    }

    /**
     * Test the property 'imageDataContentType'
     */
    @Test
    public void imageDataContentTypeTest() {
        // TODO: test imageDataContentType
    }

    /**
     * Test the property 'imageInternalFileName'
     */
    @Test
    public void imageInternalFileNameTest() {
        // TODO: test imageInternalFileName
    }

    /**
     * Test the property 'imageContentsURL'
     */
    @Test
    public void imageContentsURLTest() {
        // TODO: test imageContentsURL
    }

}
