/*
 * validateapi
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.rt;

import com.cloudmersive.client.rt.model.UserAgentValidateRequest;
import com.cloudmersive.client.rt.model.UserAgentValidateResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.springframework.web.client.RestClientException;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserAgentApi
 */
@Disabled
class UserAgentApiTest {

    private final UserAgentApi api = new UserAgentApi();

    
    /**
     * Parse an HTTP User-Agent string, identify robots
     *
     * Uses a parsing system and database to parse the User-Agent into its structured component parts, such as Browser, Browser Version, Browser Engine, Operating System, and importantly, Robot identification.
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void userAgentParseTest() {
        UserAgentValidateRequest request = null;

        UserAgentValidateResponse response = api.userAgentParse(request);

        // TODO: test validations
    }
    
}
