/*
 * currencyapi
 * The currency APIs help you retrieve exchange rates and convert prices between currencies easily.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.rt.model;

import java.util.Objects;
import java.util.Arrays;
import com.cloudmersive.client.rt.model.AvailableCurrency;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Result of performing an enumerate currencies operation
 */
@ApiModel(description = "Result of performing an enumerate currencies operation")
@JsonPropertyOrder({
  AvailableCurrencyResponse.JSON_PROPERTY_CURRENCIES
})
@JsonTypeName("AvailableCurrencyResponse")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-11-14T13:47:32.732-08:00[America/Los_Angeles]")
public class AvailableCurrencyResponse {
  public static final String JSON_PROPERTY_CURRENCIES = "Currencies";
  private List<AvailableCurrency> currencies = null;


  public AvailableCurrencyResponse currencies(List<AvailableCurrency> currencies) {
    
    this.currencies = currencies;
    return this;
  }

  public AvailableCurrencyResponse addCurrenciesItem(AvailableCurrency currenciesItem) {
    if (this.currencies == null) {
      this.currencies = new ArrayList<AvailableCurrency>();
    }
    this.currencies.add(currenciesItem);
    return this;
  }

   /**
   * List of available currencies from the API
   * @return currencies
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "List of available currencies from the API")
  @JsonProperty(JSON_PROPERTY_CURRENCIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<AvailableCurrency> getCurrencies() {
    return currencies;
  }


  public void setCurrencies(List<AvailableCurrency> currencies) {
    this.currencies = currencies;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AvailableCurrencyResponse availableCurrencyResponse = (AvailableCurrencyResponse) o;
    return Objects.equals(this.currencies, availableCurrencyResponse.currencies);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currencies);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AvailableCurrencyResponse {\n");
    sb.append("    currencies: ").append(toIndentedString(currencies)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

