/*
 * convertapi
 * Convert API lets you effortlessly convert file formats and types.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.rt.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Result of base 64 encoding
 */
@ApiModel(description = "Result of base 64 encoding")
@JsonPropertyOrder({
  Base64EncodeResponse.JSON_PROPERTY_SUCCESSFUL,
  Base64EncodeResponse.JSON_PROPERTY_BASE64_TEXT_CONTENT_RESULT
})
@JsonTypeName("Base64EncodeResponse")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-06-01T10:54:02.994-07:00[America/Los_Angeles]")
public class Base64EncodeResponse {
  public static final String JSON_PROPERTY_SUCCESSFUL = "Successful";
  private Boolean successful;

  public static final String JSON_PROPERTY_BASE64_TEXT_CONTENT_RESULT = "Base64TextContentResult";
  private String base64TextContentResult;


  public Base64EncodeResponse successful(Boolean successful) {
    
    this.successful = successful;
    return this;
  }

   /**
   * True if successful, false otherwise
   * @return successful
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "True if successful, false otherwise")
  @JsonProperty(JSON_PROPERTY_SUCCESSFUL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getSuccessful() {
    return successful;
  }


  public void setSuccessful(Boolean successful) {
    this.successful = successful;
  }


  public Base64EncodeResponse base64TextContentResult(String base64TextContentResult) {
    
    this.base64TextContentResult = base64TextContentResult;
    return this;
  }

   /**
   * Result of performing a base 64 encoding operation, a text string representing the encoded original file content
   * @return base64TextContentResult
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Result of performing a base 64 encoding operation, a text string representing the encoded original file content")
  @JsonProperty(JSON_PROPERTY_BASE64_TEXT_CONTENT_RESULT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBase64TextContentResult() {
    return base64TextContentResult;
  }


  public void setBase64TextContentResult(String base64TextContentResult) {
    this.base64TextContentResult = base64TextContentResult;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Base64EncodeResponse base64EncodeResponse = (Base64EncodeResponse) o;
    return Objects.equals(this.successful, base64EncodeResponse.successful) &&
        Objects.equals(this.base64TextContentResult, base64EncodeResponse.base64TextContentResult);
  }

  @Override
  public int hashCode() {
    return Objects.hash(successful, base64TextContentResult);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Base64EncodeResponse {\n");
    sb.append("    successful: ").append(toIndentedString(successful)).append("\n");
    sb.append("    base64TextContentResult: ").append(toIndentedString(base64TextContentResult)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

