/*
 * convertapi
 * Convert API lets you effortlessly convert file formats and types.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.rt.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Object representing one document
 */
@JsonPropertyOrder({
  DocumentItem.JSON_PROPERTY_DOCUMENT_FILE_NAME,
  DocumentItem.JSON_PROPERTY_DOCUMENT_CONTENT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-10-22T03:16:28.653440600Z[Etc/UTC]", comments = "Generator version: 7.9.0")
public class DocumentItem {
  public static final String JSON_PROPERTY_DOCUMENT_FILE_NAME = "DocumentFileName";
  private String documentFileName;

  public static final String JSON_PROPERTY_DOCUMENT_CONTENT = "DocumentContent";
  private byte[] documentContent;

  public DocumentItem() {
  }

  public DocumentItem documentFileName(String documentFileName) {
    
    this.documentFileName = documentFileName;
    return this;
  }

  /**
   * File name of the document
   * @return documentFileName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DOCUMENT_FILE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDocumentFileName() {
    return documentFileName;
  }


  @JsonProperty(JSON_PROPERTY_DOCUMENT_FILE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDocumentFileName(String documentFileName) {
    this.documentFileName = documentFileName;
  }

  public DocumentItem documentContent(byte[] documentContent) {
    
    this.documentContent = documentContent;
    return this;
  }

  /**
   * Contents of the document as a binary byte array
   * @return documentContent
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DOCUMENT_CONTENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public byte[] getDocumentContent() {
    return documentContent;
  }


  @JsonProperty(JSON_PROPERTY_DOCUMENT_CONTENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDocumentContent(byte[] documentContent) {
    this.documentContent = documentContent;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DocumentItem documentItem = (DocumentItem) o;
    return Objects.equals(this.documentFileName, documentItem.documentFileName) &&
        Arrays.equals(this.documentContent, documentItem.documentContent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(documentFileName, Arrays.hashCode(documentContent));
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DocumentItem {\n");
    sb.append("    documentFileName: ").append(toIndentedString(documentFileName)).append("\n");
    sb.append("    documentContent: ").append(toIndentedString(documentContent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

