/*
 * validateapi
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.rt.model;

import java.util.Objects;
import java.util.Arrays;
import com.cloudmersive.client.rt.model.XxeDetectionResult;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Result of performing a batch XXE detection operation
 */
@JsonPropertyOrder({
  XxeDetectionBatchResponse.JSON_PROPERTY_RESULT_ITEMS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-10-22T03:15:48.283468600Z[Etc/UTC]", comments = "Generator version: 7.9.0")
public class XxeDetectionBatchResponse {
  public static final String JSON_PROPERTY_RESULT_ITEMS = "ResultItems";
  private List<XxeDetectionResult> resultItems = new ArrayList<>();

  public XxeDetectionBatchResponse() {
  }

  public XxeDetectionBatchResponse resultItems(List<XxeDetectionResult> resultItems) {
    
    this.resultItems = resultItems;
    return this;
  }

  public XxeDetectionBatchResponse addResultItemsItem(XxeDetectionResult resultItemsItem) {
    if (this.resultItems == null) {
      this.resultItems = new ArrayList<>();
    }
    this.resultItems.add(resultItemsItem);
    return this;
  }

  /**
   * Results from performing a batch XSS protection operation
   * @return resultItems
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESULT_ITEMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<XxeDetectionResult> getResultItems() {
    return resultItems;
  }


  @JsonProperty(JSON_PROPERTY_RESULT_ITEMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResultItems(List<XxeDetectionResult> resultItems) {
    this.resultItems = resultItems;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    XxeDetectionBatchResponse xxeDetectionBatchResponse = (XxeDetectionBatchResponse) o;
    return Objects.equals(this.resultItems, xxeDetectionBatchResponse.resultItems);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resultItems);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class XxeDetectionBatchResponse {\n");
    sb.append("    resultItems: ").append(toIndentedString(resultItems)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

