/*
 * convertapi
 * Convert API lets you effortlessly convert file formats and types.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.model;

import com.cloudmersive.client.model.DocumentValidationError;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AutodetectDocumentValidationResult
 */
public class AutodetectDocumentValidationResultTest {
    private final AutodetectDocumentValidationResult model = new AutodetectDocumentValidationResult();

    /**
     * Model tests for AutodetectDocumentValidationResult
     */
    @Test
    public void testAutodetectDocumentValidationResult() {
        // TODO: test AutodetectDocumentValidationResult
    }

    /**
     * Test the property 'fileFormatExtension'
     */
    @Test
    public void fileFormatExtensionTest() {
        // TODO: test fileFormatExtension
    }

    /**
     * Test the property 'documentIsValid'
     */
    @Test
    public void documentIsValidTest() {
        // TODO: test documentIsValid
    }

    /**
     * Test the property 'errorCount'
     */
    @Test
    public void errorCountTest() {
        // TODO: test errorCount
    }

    /**
     * Test the property 'warningCount'
     */
    @Test
    public void warningCountTest() {
        // TODO: test warningCount
    }

    /**
     * Test the property 'errorsAndWarnings'
     */
    @Test
    public void errorsAndWarningsTest() {
        // TODO: test errorsAndWarnings
    }

}
