/*
 * currencyapi
 * The currency APIs help you retrieve exchange rates and convert prices between currencies easily.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ConvertedCurrencyResult
 */
public class ConvertedCurrencyResultTest {
    private final ConvertedCurrencyResult model = new ConvertedCurrencyResult();

    /**
     * Model tests for ConvertedCurrencyResult
     */
    @Test
    public void testConvertedCurrencyResult() {
        // TODO: test ConvertedCurrencyResult
    }

    /**
     * Test the property 'convertedPrice'
     */
    @Test
    public void convertedPriceTest() {
        // TODO: test convertedPrice
    }

    /**
     * Test the property 'isOCurrencyCode'
     */
    @Test
    public void isOCurrencyCodeTest() {
        // TODO: test isOCurrencyCode
    }

    /**
     * Test the property 'currencySymbol'
     */
    @Test
    public void currencySymbolTest() {
        // TODO: test currencySymbol
    }

    /**
     * Test the property 'formattedPriceAsString'
     */
    @Test
    public void formattedPriceAsStringTest() {
        // TODO: test formattedPriceAsString
    }

}
