/*
 * convertapi
 * Convert API lets you effortlessly convert file formats and types.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.model;

import com.cloudmersive.client.model.ZipDirectory;
import com.cloudmersive.client.model.ZipFile;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CreateZipArchiveRequest
 */
public class CreateZipArchiveRequestTest {
    private final CreateZipArchiveRequest model = new CreateZipArchiveRequest();

    /**
     * Model tests for CreateZipArchiveRequest
     */
    @Test
    public void testCreateZipArchiveRequest() {
        // TODO: test CreateZipArchiveRequest
    }

    /**
     * Test the property 'filesInZip'
     */
    @Test
    public void filesInZipTest() {
        // TODO: test filesInZip
    }

    /**
     * Test the property 'directoriesInZip'
     */
    @Test
    public void directoriesInZipTest() {
        // TODO: test directoriesInZip
    }

}
