/*
 * convertapi
 * Convert API lets you effortlessly convert file formats and types.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DocxStyle
 */
public class DocxStyleTest {
    private final DocxStyle model = new DocxStyle();

    /**
     * Model tests for DocxStyle
     */
    @Test
    public void testDocxStyle() {
        // TODO: test DocxStyle
    }

    /**
     * Test the property 'styleID'
     */
    @Test
    public void styleIDTest() {
        // TODO: test styleID
    }

    /**
     * Test the property 'path'
     */
    @Test
    public void pathTest() {
        // TODO: test path
    }

    /**
     * Test the property 'bold'
     */
    @Test
    public void boldTest() {
        // TODO: test bold
    }

    /**
     * Test the property 'italic'
     */
    @Test
    public void italicTest() {
        // TODO: test italic
    }

    /**
     * Test the property 'underline'
     */
    @Test
    public void underlineTest() {
        // TODO: test underline
    }

    /**
     * Test the property 'fontSize'
     */
    @Test
    public void fontSizeTest() {
        // TODO: test fontSize
    }

    /**
     * Test the property 'fontFamily'
     */
    @Test
    public void fontFamilyTest() {
        // TODO: test fontFamily
    }

}
