/*
 * convertapi
 * Convert API lets you effortlessly convert file formats and types.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for FindRegexMatch
 */
public class FindRegexMatchTest {
    private final FindRegexMatch model = new FindRegexMatch();

    /**
     * Model tests for FindRegexMatch
     */
    @Test
    public void testFindRegexMatch() {
        // TODO: test FindRegexMatch
    }

    /**
     * Test the property 'characterOffsetStart'
     */
    @Test
    public void characterOffsetStartTest() {
        // TODO: test characterOffsetStart
    }

    /**
     * Test the property 'characterOffsetEnd'
     */
    @Test
    public void characterOffsetEndTest() {
        // TODO: test characterOffsetEnd
    }

    /**
     * Test the property 'containingLine'
     */
    @Test
    public void containingLineTest() {
        // TODO: test containingLine
    }

    /**
     * Test the property 'matchValue'
     */
    @Test
    public void matchValueTest() {
        // TODO: test matchValue
    }

    /**
     * Test the property 'matchGroups'
     */
    @Test
    public void matchGroupsTest() {
        // TODO: test matchGroups
    }

}
