/*
 * convertapi
 * Convert API lets you effortlessly convert file formats and types.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.model;

import com.cloudmersive.client.model.DocxCellStyle;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetXlsxStylesResponse
 */
public class GetXlsxStylesResponseTest {
    private final GetXlsxStylesResponse model = new GetXlsxStylesResponse();

    /**
     * Model tests for GetXlsxStylesResponse
     */
    @Test
    public void testGetXlsxStylesResponse() {
        // TODO: test GetXlsxStylesResponse
    }

    /**
     * Test the property 'successful'
     */
    @Test
    public void successfulTest() {
        // TODO: test successful
    }

    /**
     * Test the property 'cellStyles'
     */
    @Test
    public void cellStylesTest() {
        // TODO: test cellStyles
    }

}
