/*
 * videoapi
 * The video APIs help you convert, encode, and transcode videos.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.model;

import com.cloudmersive.client.model.StillFrame;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for StillFramesResult
 */
public class StillFramesResultTest {
    private final StillFramesResult model = new StillFramesResult();

    /**
     * Model tests for StillFramesResult
     */
    @Test
    public void testStillFramesResult() {
        // TODO: test StillFramesResult
    }

    /**
     * Test the property 'successful'
     */
    @Test
    public void successfulTest() {
        // TODO: test successful
    }

    /**
     * Test the property 'totalFrames'
     */
    @Test
    public void totalFramesTest() {
        // TODO: test totalFrames
    }

    /**
     * Test the property 'stillFrames'
     */
    @Test
    public void stillFramesTest() {
        // TODO: test stillFrames
    }

}
