/*
 * convertapi
 * Convert API lets you effortlessly convert file formats and types.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for XmlQueryWithXQueryMultiResult
 */
public class XmlQueryWithXQueryMultiResultTest {
    private final XmlQueryWithXQueryMultiResult model = new XmlQueryWithXQueryMultiResult();

    /**
     * Model tests for XmlQueryWithXQueryMultiResult
     */
    @Test
    public void testXmlQueryWithXQueryMultiResult() {
        // TODO: test XmlQueryWithXQueryMultiResult
    }

    /**
     * Test the property 'successful'
     */
    @Test
    public void successfulTest() {
        // TODO: test successful
    }

    /**
     * Test the property 'resultingXml'
     */
    @Test
    public void resultingXmlTest() {
        // TODO: test resultingXml
    }

    /**
     * Test the property 'errorMessage'
     */
    @Test
    public void errorMessageTest() {
        // TODO: test errorMessage
    }

}
