/*
 * validateapi
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for XssProtectionResult
 */
public class XssProtectionResultTest {
    private final XssProtectionResult model = new XssProtectionResult();

    /**
     * Model tests for XssProtectionResult
     */
    @Test
    public void testXssProtectionResult() {
        // TODO: test XssProtectionResult
    }

    /**
     * Test the property 'successful'
     */
    @Test
    public void successfulTest() {
        // TODO: test successful
    }

    /**
     * Test the property 'containedXss'
     */
    @Test
    public void containedXssTest() {
        // TODO: test containedXss
    }

    /**
     * Test the property 'originalInput'
     */
    @Test
    public void originalInputTest() {
        // TODO: test originalInput
    }

    /**
     * Test the property 'normalizedResult'
     */
    @Test
    public void normalizedResultTest() {
        // TODO: test normalizedResult
    }

}
