/*
 * convertapi
 * Convert API lets you effortlessly convert file formats and types.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ZipEncryptionAdvancedRequest
 */
public class ZipEncryptionAdvancedRequestTest {
    private final ZipEncryptionAdvancedRequest model = new ZipEncryptionAdvancedRequest();

    /**
     * Model tests for ZipEncryptionAdvancedRequest
     */
    @Test
    public void testZipEncryptionAdvancedRequest() {
        // TODO: test ZipEncryptionAdvancedRequest
    }

    /**
     * Test the property 'inputFileContents'
     */
    @Test
    public void inputFileContentsTest() {
        // TODO: test inputFileContents
    }

    /**
     * Test the property 'password'
     */
    @Test
    public void passwordTest() {
        // TODO: test password
    }

    /**
     * Test the property 'encryptionAlgorithm'
     */
    @Test
    public void encryptionAlgorithmTest() {
        // TODO: test encryptionAlgorithm
    }

}
